const ICAR_ADVISORY='https://icar.gov.in/en/icar-kharif-agro-advisories-farmers-2025';
const ICAR_IFC='https://icar.gov.in/hi/node/10817';
const PLANTVILLAGE='https://github.com/spMohanty/PlantVillage-Dataset';

const CATALOG={
 'Rice___Brown_spot':{crop:'Rice',title:'Rice brown spot',summary:'Fungal leaf and grain disease; confirm field symptoms and consider seed health, nutrition and moisture management.',ipm:['Use healthy seed and balanced nutrition.','Remove volunteer/infected residues where practical.','Avoid prolonged moisture or nutrient stress.'],pesticides:[],sources:[{name:'ICAR Kharif Agro-Advisories 2025',url:ICAR_ADVISORY}]},
 'Rice___Blast':{crop:'Rice',title:'Rice blast',summary:'Blast can affect leaves, nodes and panicles. Image classification is a screening aid; field confirmation is important.',ipm:['Use balanced nitrogen and avoid excessive nitrogen.','Monitor lesions on leaves and panicles regularly.','Manage field humidity and avoid unnecessary prolonged leaf wetness.'],pesticides:[{product:'Tricyclazole',formulation:'Tricyclazole',dose:'Seed treatment: 2 g/kg seed',source:'ICAR Kharif Agro-Advisories 2025',url:ICAR_ADVISORY},{product:'Propiconazole 25 EC',formulation:'25 EC',dose:'Spray: 500 ml/ha',source:'ICAR Kharif Agro-Advisories 2025',url:ICAR_ADVISORY}],sources:[{name:'ICAR Kharif Agro-Advisories 2025',url:ICAR_ADVISORY},{name:'ICAR-NRCIPM pesticide/fungicide calculators',url:ICAR_IFC}]},
 'Rice___Sheath_Blight':{crop:'Rice',title:'Rice sheath blight',summary:'Sheath blight is favored by dense canopy and humid conditions; verify the characteristic sheath lesions.',ipm:['Maintain appropriate plant density and avoid excessive nitrogen.','Improve field observation and canopy ventilation where feasible.','Remove severely affected residues after harvest where practical.'],pesticides:[{product:'Trifloxystrobin 25% + Tebuconazole 50%',formulation:'WG',dose:'0.5 g/L',source:'ICAR Kharif Agro-Advisories 2025',url:ICAR_ADVISORY},{product:'Carbendazim 50% WP',formulation:'WP',dose:'2 g/L on affected areas',source:'ICAR Kharif Agro-Advisories 2025',url:ICAR_ADVISORY}],sources:[{name:'ICAR Kharif Agro-Advisories 2025',url:ICAR_ADVISORY},{name:'ICAR-NRCIPM pesticide/fungicide calculators',url:ICAR_IFC}]},
 'Tomato___Early_blight':{crop:'Tomato',title:'Tomato early blight',summary:'Early blight is commonly associated with leaf spots and concentric lesions. Confirm symptoms before treatment.',ipm:['Remove heavily infected lower leaves and manage crop residues.','Improve spacing and canopy ventilation.','Avoid prolonged leaf wetness where practical.'],pesticides:[{product:'Copper oxychloride',formulation:'Fungicide',dose:'3 g/L',source:'ICAR Kharif Agro-Advisories 2025',url:ICAR_ADVISORY},{product:'Metalaxyl 4% + Mancozeb 64% WP',formulation:'WP',dose:'1.5 g/L',source:'ICAR Kharif Agro-Advisories 2025',url:ICAR_ADVISORY}],sources:[{name:'ICAR Kharif Agro-Advisories 2025',url:ICAR_ADVISORY},{name:'ICAR tomato field intervention report',url:'https://icar.gov.in/en/node/4685'}]},
 'Tomato___Late_blight':{crop:'Tomato',title:'Tomato late blight',summary:'Late blight can progress rapidly under cool, wet conditions. Confirm urgently when symptoms fit.',ipm:['Scout frequently during cool/wet weather.','Improve air movement and avoid overhead irrigation where possible.','Remove badly affected plant material safely.'],pesticides:[{product:'Cymoxanil + Mancozeb',formulation:'Fungicide mixture',dose:'2 g/L',source:'ICAR tomato field intervention report',url:'https://icar.gov.in/en/node/4685'},{product:'Pyraclostrobin + Metiram',formulation:'Fungicide mixture',dose:'2 g/L',source:'ICAR tomato field intervention report',url:'https://icar.gov.in/en/node/4685'}],sources:[{name:'ICAR tomato field intervention report',url:'https://icar.gov.in/en/node/4685'}]},
 'Tomato___Bacterial_spot':{crop:'Tomato',title:'Tomato bacterial spot',summary:'Bacterial spot requires careful confirmation because visual symptoms can overlap with other leaf-spot diseases.',ipm:['Use clean seed and transplants.','Avoid working wet foliage and reduce splash dispersal.','Remove severely affected plant material and sanitize tools.'],pesticides:[],sources:[{name:'ICAR Kharif Agro-Advisories 2025',url:ICAR_ADVISORY}]},
 'Tomato___Leaf_Mold':{crop:'Tomato',title:'Tomato leaf mold',summary:'Leaf mold is favored by humid conditions and commonly begins on lower leaf surfaces.',ipm:['Improve greenhouse/field ventilation.','Reduce leaf wetness and excess humidity.','Remove affected leaves and manage residues.'],pesticides:[],sources:[{name:'ICAR Kharif Agro-Advisories 2025',url:ICAR_ADVISORY}]},
 'Tomato___Septoria_leaf_spot':{crop:'Tomato',title:'Tomato Septoria leaf spot',summary:'Leaf-spot symptoms should be confirmed against field conditions and lesion appearance.',ipm:['Remove infected lower leaves.','Improve airflow and sanitation.','Avoid splash irrigation.'],pesticides:[],sources:[{name:'ICAR Kharif Agro-Advisories 2025',url:ICAR_ADVISORY}]},
 'Pepper,_bell___Bacterial_spot':{crop:'Bell pepper',title:'Pepper bacterial spot',summary:'Bacterial spot can spread through splash and contaminated planting material.',ipm:['Use clean planting material.','Avoid handling wet plants.','Sanitize tools and remove severely affected tissue.'],pesticides:[],sources:[{name:'ICAR Kharif Agro-Advisories 2025',url:ICAR_ADVISORY}]},
 'Chilli___Leaf_spot':{crop:'Chilli',title:'Chilli leaf spot',summary:'Leaf-spot symptoms should be confirmed before chemical control.',ipm:['Scout leaves regularly.','Maintain field sanitation and airflow.','Avoid unnecessary leaf wetness.'],pesticides:[{product:'Chlorothalonil 75% WP',formulation:'WP',dose:'2 g/L water',source:'ICAR Kharif Agro-Advisories 2025',url:ICAR_ADVISORY}],sources:[{name:'ICAR Kharif Agro-Advisories 2025',url:ICAR_ADVISORY},{name:'ICAR-NRCIPM pesticide/fungicide calculators',url:ICAR_IFC}]},
 'Potato___Early_blight':{crop:'Potato',title:'Potato early blight',summary:'Early blight screening should be confirmed with field symptoms and crop stage.',ipm:['Use healthy seed and balanced nutrition.','Remove infected residues after harvest.','Monitor lower leaves and crop stress.'],pesticides:[],sources:[{name:'ICAR Kharif Agro-Advisories 2025',url:ICAR_ADVISORY}]},
 'Potato___Late_blight':{crop:'Potato',title:'Potato late blight',summary:'Late blight can spread rapidly under cool, wet conditions and needs prompt field confirmation.',ipm:['Scout after rain/high humidity.','Reduce prolonged leaf wetness where practical.','Remove heavily affected material safely.'],pesticides:[],sources:[{name:'ICAR Kharif Agro-Advisories 2025',url:ICAR_ADVISORY},{name:'ICAR-NRCIPM pesticide/fungicide calculators',url:ICAR_IFC}]},
 'Corn_(maize)___Common_rust_':{crop:'Maize',title:'Maize common rust',summary:'Rust produces characteristic pustules; confirm field symptoms before treatment.',ipm:['Scout leaves early and monitor spread.','Maintain balanced nutrition and crop vigor.','Use locally recommended resistant varieties when available.'],pesticides:[],sources:[{name:'ICAR Kharif Agro-Advisories 2025',url:ICAR_ADVISORY}]},
 'Corn_(maize)___Northern_Leaf_Blight':{crop:'Maize',title:'Maize northern leaf blight',summary:'Long lesions on leaves can indicate northern leaf blight; confirm against field symptoms.',ipm:['Use resistant varieties where available.','Manage crop residues.','Monitor lower leaves and canopy spread.'],pesticides:[],sources:[{name:'ICAR Kharif Agro-Advisories 2025',url:ICAR_ADVISORY}]},
 'Grape___Black_rot':{crop:'Grape',title:'Grape black rot',summary:'Confirm black rot from characteristic lesions and fruit symptoms.',ipm:['Remove mummified fruit and infected debris.','Improve canopy airflow.','Monitor after wet weather.'],pesticides:[],sources:[{name:'ICAR Kharif Agro-Advisories 2025',url:ICAR_ADVISORY}]},
 'Grape___Esca_(Black_Measles)':{crop:'Grape',title:'Grape Esca / black measles',summary:'Esca-like symptoms can have multiple causes; field diagnosis is important.',ipm:['Remove and destroy severely affected material where advised locally.','Use clean planting material.','Seek local horticulture extension confirmation.'],pesticides:[],sources:[{name:'ICAR Kharif Agro-Advisories 2025',url:ICAR_ADVISORY}]},
 'Apple___Apple_scab':{crop:'Apple',title:'Apple scab',summary:'Scab management depends strongly on local weather and orchard monitoring.',ipm:['Sanitize fallen leaves.','Improve orchard airflow and pruning.','Use local horticulture advisory for timing.'],pesticides:[],sources:[{name:'ICAR Kharif Agro-Advisories 2025',url:ICAR_ADVISORY}]},
 'Apple___Black_rot':{crop:'Apple',title:'Apple black rot',summary:'Confirm symptoms and manage infected plant material and orchard sanitation.',ipm:['Remove mummified fruit and dead wood where advised.','Maintain orchard sanitation.','Seek local horticulture guidance.'],pesticides:[],sources:[{name:'ICAR Kharif Agro-Advisories 2025',url:ICAR_ADVISORY}]},
 'Apple___Cedar_apple_rust':{crop:'Apple',title:'Apple cedar apple rust',summary:'Rust requires diagnosis and local orchard management guidance.',ipm:['Monitor new foliage and fruiting structures.','Manage alternate hosts where appropriate and legal.','Use local horticulture advisory for fungicide timing.'],pesticides:[],sources:[{name:'ICAR Kharif Agro-Advisories 2025',url:ICAR_ADVISORY}]},
 'Squash___Powdery_mildew':{crop:'Squash',title:'Squash powdery mildew',summary:'Powdery mildew commonly appears as white powdery growth on leaves.',ipm:['Improve airflow and avoid dense canopy.','Monitor early symptoms.','Use locally registered products only when needed.'],pesticides:[],sources:[{name:'ICAR Kharif Agro-Advisories 2025',url:ICAR_ADVISORY}]},
 'Strawberry___Leaf_scorch':{crop:'Strawberry',title:'Strawberry leaf scorch',summary:'Confirm the cause because scorch-like symptoms can be caused by multiple stresses.',ipm:['Check irrigation, salts and nutrient balance.','Remove severely affected leaves.','Seek local horticulture confirmation.'],pesticides:[],sources:[{name:'ICAR Kharif Agro-Advisories 2025',url:ICAR_ADVISORY}]}
};

export function normalizeLabel(label){return String(label||'').replace(/\s+/g,' ').trim();}
const HISTORICAL=[{name:'Vrikshayurveda (historical agricultural text)',note:'Historical reference for plant cultivation and plant care; not a modern pesticide prescription.'},{name:'Krishi-Parashara (historical agricultural text)',note:'Historical reference on agriculture, crops and cultivation; not a modern pesticide prescription.'}];
export function getKnowledge(label,crop=''){
 const key=normalizeLabel(label); const exact=CATALOG[key];
 if(exact) return {...exact,label:key,historicalReferences:HISTORICAL};
 const lower=key.toLowerCase();
 if(lower.includes('healthy')) return {label:key,crop:crop||inferCrop(key),historicalReferences:HISTORICAL,title:'Likely healthy leaf',summary:'The classifier found a healthy class. Continue routine scouting because a single image cannot prove whole-field health.',ipm:['Continue regular field scouting.','Monitor new growth and crop stage.','Use weather and field observations to identify emerging risks.'],pesticides:[],sources:[{name:'PlantVillage Dataset',url:PLANTVILLAGE}]};
 return {label:key,crop:crop||inferCrop(key),historicalReferences:HISTORICAL,title:pretty(key),summary:'The model result is a preliminary image-screening result. Confirm the disease with field symptoms and local agricultural extension guidance before treatment.',ipm:['Compare several affected plants and healthy plants.','Check leaf underside, stems, roots and crop stage.','Prefer sanitation, monitoring and integrated pest management while confirming the diagnosis.'],pesticides:[],sources:[{name:'PlantVillage Dataset',url:PLANTVILLAGE},{name:'ICAR-NRCIPM pesticide/fungicide calculators',url:ICAR_IFC}]};
}
function inferCrop(label){const x=label.toLowerCase();for(const c of ['rice','tomato','potato','corn','maize','grape','apple','pepper','chilli','cotton','wheat','soybean','squash','strawberry','peach','cherry','blueberry','raspberry','orange'])if(x.includes(c))return c;return '';}
function pretty(label){return label.replace(/___/g,' — ').replace(/_/g,' ').replace(/\s+/g,' ').trim();}

export function assistantAnswer(question,{scan,language='English'}={}){
 const q=String(question||'').toLowerCase(); const k=scan?.knowledge; const prefix=language==='Telugu'?'స్కాన్ ఫలితం: ':language==='Hindi'?'स्कैन परिणाम: ':'Scan result: ';
 if(k && (q.includes('scan')||q.includes('disease')||q.includes('treatment')||q.includes('medicine')||q.includes('pesticide')||q.includes('fungicide')||q.includes('what'))){
   const chemical=k.pesticides?.length?`Authoritative options in the linked source include: ${k.pesticides.map(p=>`${p.product} — ${p.dose}`).join('; ')}. Use only if the current local label/registration permits it.`:'No pesticide is displayed because this knowledge entry does not contain a verified product/dose pair. Use the ICAR-NRCIPM calculator or local extension advice for current label claims.';
   return `${prefix}${k.title}. ${k.summary} ${k.ipm.join(' ')} ${chemical}`;
 }
 if(q.includes('yellow')||q.includes('pale')) return 'Yellowing can come from nutrient imbalance, water stress, root problems, pests or disease. Compare affected and healthy plants, inspect the underside of leaves and roots, and use a confirmed diagnosis before applying chemicals.';
 if(q.includes('pest')||q.includes('insect')) return 'For early pest detection, inspect new shoots, leaf undersides and growing points. Look for insects, eggs, webbing, feeding injury and sticky residues. Use integrated pest management and treat only after correct identification.';
 if(q.includes('weather')||q.includes('rain')||q.includes('humidity')) return 'Rain, humidity, temperature and leaf wetness can change disease risk. Weather is a risk signal, not a diagnosis; combine it with crop stage and field observations.';
 return k?`${prefix}${k.title}. Ask me about symptoms, treatment options, pesticides, prevention or the government support linked to this crop.`:'Tell me the crop, symptom, growth stage and what you observed on the leaves. I can then give a structured crop-health answer and point to the relevant agricultural source.';
}
