import 'dotenv/config';
import express from 'express'; import cors from 'cors'; import helmet from 'helmet'; import rateLimit from 'express-rate-limit'; import multer from 'multer'; import crypto from 'node:crypto'; import path from 'node:path'; import fs from 'node:fs';
import db from './db.js'; import {normalizeContact,contactMethod,hashOtp,createToken,authRequired,userByContact,safeUser,passwordOk,hashPassword,verifyPassword} from './auth.js'; import {sendOtp} from './mailer.js'; import {diagnoseImage} from './ai.js';
import {getKnowledge,assistantAnswer} from './knowledge.js';
const app=express(); const PORT=Number(process.env.PORT||4000); const ROOT=path.resolve(new URL('..',import.meta.url).pathname); const uploadDir=path.resolve(ROOT,'uploads'); fs.mkdirSync(uploadDir,{recursive:true});
app.use(helmet({crossOriginResourcePolicy:false})); app.use(cors({origin:true,methods:['GET','POST','PATCH','OPTIONS'],allowedHeaders:['Content-Type','Authorization']})); app.use(express.json({limit:'2mb'}));
const limiter=rateLimit({windowMs:15*60*1000,max:120,standardHeaders:true,legacyHeaders:false}); app.use('/api/',limiter);
const upload=multer({dest:uploadDir,limits:{fileSize:8*1024*1024},fileFilter:(req,file,cb)=>cb(null,/^image\/(jpeg|png|webp|jpg)$/.test(file.mimetype))});
app.get('/api/health',(req,res)=>res.json({ok:true,service:'AgriVision AI backend',time:new Date().toISOString(),ai:process.env.HF_TOKEN?'huggingface':'not_configured',model:process.env.HF_MODEL||'linkanjarad/mobilenet_v2_1.0_224-plant-disease-identification',knowledge:true,subsidies:true,assistant:true}));
app.get('/api/ai/status',(req,res)=>res.json({configured:!!process.env.HF_TOKEN,model:process.env.HF_MODEL||'linkanjarad/mobilenet_v2_1.0_224-plant-disease-identification',dataset:'PlantVillage / 38 classes',message:process.env.HF_TOKEN?'AI inference is configured.':'Set HF_TOKEN in backend/.env to enable live image inference.'}));
function makeOtp(){return String(crypto.randomInt(100000,1000000));}
app.post('/api/auth/request-otp',async(req,res)=>{try{const contact=normalizeContact(req.body.contact),method=req.body.method||contactMethod(contact);if(!method||contactMethod(contact)!==method)return res.status(400).json({message:'Invalid email or phone number.'});const existing=userByContact(contact);const purpose='login_or_register';const recent=db.prepare('SELECT created_at FROM otp_codes WHERE contact=? AND method=? AND purpose=? ORDER BY id DESC LIMIT 1').get(contact,method,purpose);if(recent && Date.now()-Date.parse(recent.created_at)<45*1000)return res.status(429).json({message:'Please wait before requesting another OTP.'});const otp=makeOtp();db.prepare('INSERT INTO otp_codes(contact,method,code_hash,purpose,expires_at) VALUES(?,?,?,?,?)').run(contact,method,hashOtp(otp),purpose,Date.now()+5*60*1000);const delivery=await sendOtp({method,contact,otp,purpose});const out={message:'OTP generated.',deliveryMessage:delivery.delivered?`OTP sent to your ${method}.`:`Development mode: OTP created for ${method}.`,existingUser:!!existing,requestId:crypto.randomUUID()};if(delivery.development)out.developmentOtp=otp;res.json(out);}catch(e){res.status(500).json({message:e.message||'Unable to send OTP.'});}});
app.post('/api/auth/verify-otp',(req,res)=>{try{const contact=normalizeContact(req.body.contact),method=req.body.method||contactMethod(contact),otp=String(req.body.otp||'');const row=db.prepare('SELECT * FROM otp_codes WHERE contact=? AND method=? AND purpose=? AND consumed=0 ORDER BY id DESC LIMIT 1').get(contact,method,'login_or_register');if(!row)return res.status(400).json({message:'OTP not found. Request a new OTP.'});if(Date.now()>row.expires_at)return res.status(400).json({message:'OTP expired. Request a new one.'});if(row.attempts>=5)return res.status(429).json({message:'Too many incorrect attempts. Request a new OTP.'});db.prepare('UPDATE otp_codes SET attempts=attempts+1 WHERE id=?').run(row.id);if(hashOtp(otp)!==row.code_hash)return res.status(400).json({message:'Invalid OTP.'});db.prepare('UPDATE otp_codes SET consumed=1 WHERE id=?').run(row.id);const verificationToken=crypto.randomBytes(32).toString('hex');db.prepare('INSERT INTO otp_codes(contact,method,code_hash,purpose,expires_at) VALUES(?,?,?,?,?)').run(contact,method,hashOtp(verificationToken),'registration_verification',Date.now()+10*60*1000);res.json({verified:true,existingUser:!!userByContact(contact),verificationToken});}catch(e){res.status(500).json({message:e.message||'OTP verification failed.'});}});
app.post('/api/auth/register',async(req,res)=>{try{const contact=normalizeContact(req.body.contact),method=req.body.method||contactMethod(contact),password=req.body.password,vt=req.body.verificationToken;if(!passwordOk(password))return res.status(400).json({message:'Password must be at least 8 characters.'});const vr=db.prepare('SELECT * FROM otp_codes WHERE contact=? AND method=? AND purpose=? AND consumed=0 ORDER BY id DESC LIMIT 1').get(contact,method,'registration_verification');if(!vr||Date.now()>vr.expires_at||hashOtp(vt)!==vr.code_hash)return res.status(400).json({message:'Verification expired. Verify OTP again.'});if(userByContact(contact))return res.status(409).json({message:'An account already exists. Use Login.'});const email=method==='email'?contact:null,phone=method==='phone'?contact:null;const hash=await hashPassword(password);const info=db.prepare('INSERT INTO users(email,phone,password_hash) VALUES(?,?,?)').run(email,phone,hash);db.prepare('INSERT INTO profiles(user_id) VALUES(?)').run(info.lastInsertRowid);db.prepare('UPDATE otp_codes SET consumed=1 WHERE id=?').run(vr.id);const u=db.prepare('SELECT * FROM users WHERE id=?').get(info.lastInsertRowid);res.json({token:createToken(u),user:safeUser(u)});}catch(e){res.status(500).json({message:e.message||'Registration failed.'});}});
app.post('/api/auth/login',async(req,res)=>{try{const u=userByContact(req.body.contact);if(!u)return res.status(401).json({message:'Account not found.'});if(!(await verifyPassword(req.body.password||'',u.password_hash)))return res.status(401).json({message:'Incorrect password.'});res.json({token:createToken(u),user:safeUser(u)});}catch(e){res.status(500).json({message:'Login failed.'});}});
app.post('/api/auth/forgot-password',async(req,res)=>{try{const contact=normalizeContact(req.body.contact),method=contactMethod(contact),u=userByContact(contact);if(!u)return res.json({message:'If an account exists, a reset OTP has been generated.'});const otp=makeOtp();db.prepare('INSERT INTO otp_codes(contact,method,code_hash,purpose,expires_at) VALUES(?,?,?,?,?)').run(contact,method,hashOtp(otp),'password_reset',Date.now()+5*60*1000);const d=await sendOtp({method,contact,otp,purpose:'password_reset'});const out={message:'If an account exists, a reset OTP has been generated.'};if(d.development)out.developmentOtp=otp;res.json(out);}catch(e){res.status(500).json({message:e.message});}});
app.post('/api/auth/reset-password',async(req,res)=>{try{const contact=normalizeContact(req.body.contact),method=contactMethod(contact),otp=String(req.body.otp||''),p=req.body.newPassword||'';if(!passwordOk(p))return res.status(400).json({message:'Password must be at least 8 characters.'});const row=db.prepare('SELECT * FROM otp_codes WHERE contact=? AND method=? AND purpose=? AND consumed=0 ORDER BY id DESC LIMIT 1').get(contact,method,'password_reset');if(!row||Date.now()>row.expires_at||hashOtp(otp)!==row.code_hash)return res.status(400).json({message:'Invalid or expired reset OTP.'});const u=userByContact(contact);if(!u)return res.status(400).json({message:'Account not found.'});db.prepare('UPDATE users SET password_hash=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(await hashPassword(p),u.id);db.prepare('UPDATE otp_codes SET consumed=1 WHERE id=?').run(row.id);const nu=db.prepare('SELECT * FROM users WHERE id=?').get(u.id);res.json({token:createToken(nu),user:safeUser(nu)});}catch(e){res.status(500).json({message:e.message});}});
app.get('/api/me',authRequired,(req,res)=>{const u=db.prepare('SELECT * FROM users WHERE id=?').get(req.userId);const p=db.prepare('SELECT * FROM profiles WHERE user_id=?').get(req.userId);if(!u)return res.status(404).json({message:'User not found.'});res.json({user:safeUser(u),profile:p?{...p,crops:JSON.parse(p.crops_json||'[]')}:null});});
app.patch('/api/me',authRequired,(req,res)=>{const b=req.body||{};db.prepare('UPDATE users SET email=COALESCE(NULLIF(?,\'\'),email),phone=COALESCE(NULLIF(?,\'\'),phone),language=COALESCE(NULLIF(?,\'\'),language),updated_at=CURRENT_TIMESTAMP WHERE id=?').run(String(b.email||''),String(b.phone||''),String(b.language||''),req.userId);const p=db.prepare('SELECT * FROM profiles WHERE user_id=?').get(req.userId);const fields=['state','district','village','environment','main_crop','sowing_date','growth_stage','field_size','latitude','longitude'];const vals=fields.map(k=>b[k]??p?.[k]??null);const crops=Array.isArray(b.crops)?JSON.stringify(b.crops):(p?.crops_json||'[]');db.prepare(`INSERT INTO profiles(user_id,state,district,village,environment,crops_json,main_crop,sowing_date,growth_stage,field_size,latitude,longitude,notifications) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,COALESCE(?,0)) ON CONFLICT(user_id) DO UPDATE SET state=excluded.state,district=excluded.district,village=excluded.village,environment=excluded.environment,crops_json=excluded.crops_json,main_crop=excluded.main_crop,sowing_date=excluded.sowing_date,growth_stage=excluded.growth_stage,field_size=excluded.field_size,latitude=excluded.latitude,longitude=excluded.longitude,notifications=excluded.notifications`).run(req.userId,...vals.slice(0,5),crops,vals[5],vals[6],vals[7],vals[8],vals[9],vals[10],vals[11],b.notifications?1:0);res.json({ok:true});});
app.post('/api/scans/diagnose',authRequired,upload.single('image'),async(req,res)=>{
 if(!req.file)return res.status(400).json({message:'Image file is required.'});
 try{
  const head=await fs.readFile(req.file.path,{encoding:null});
  const ok= (head[0]===0xff&&head[1]===0xd8&&head[2]===0xff) || (head[0]===0x89&&head[1]===0x50&&head[2]===0x4e&&head[3]===0x47) || (head[0]===0x52&&head[1]===0x49&&head[2]===0x46&&head[3]===0x46&&head[8]===0x57&&head[9]===0x45&&head[10]===0x42&&head[11]===0x50);
  if(!ok) throw new Error('The uploaded file is not a valid JPEG, PNG or WebP image.');
  const crop=String(req.body.crop||'');
  const prediction=await diagnoseImage(req.file.path,crop);
  const knowledge=getKnowledge(prediction.label,prediction.crop||crop);
  const info=db.prepare('INSERT INTO scans(user_id,image_path,crop,label,confidence,severity,description,raw_json) VALUES(?,?,?,?,?,?,?,?)').run(req.userId,req.file.filename,crop,prediction.label,prediction.confidence,prediction.severity,prediction.description,JSON.stringify({...prediction.raw,top3:prediction.top3||[]}));
  res.json({scanId:info.lastInsertRowid,prediction,knowledge});
 }catch(e){try{await fs.unlink(req.file.path)}catch{};res.status(502).json({message:e.message||'AI analysis failed.'});}
});
app.get('/api/scans/:id/knowledge',authRequired,(req,res)=>{const s=db.prepare('SELECT * FROM scans WHERE id=? AND user_id=?').get(req.params.id,req.userId);if(!s)return res.status(404).json({message:'Scan not found.'});res.json({knowledge:getKnowledge(s.label,s.crop)});});
app.post('/api/assistant',authRequired,(req,res)=>{try{const q=String(req.body.question||'').trim();if(!q)return res.status(400).json({message:'Question is required.'});let scan=null;if(req.body.scanLabel){scan={label:req.body.scanLabel,knowledge:getKnowledge(req.body.scanLabel,req.body.crop||'')}};const answer=assistantAnswer(q,{scan,language:req.body.language||'English'});res.json({answer,source:'AgriVision agricultural knowledge base',knowledge:scan?.knowledge||null});}catch(e){res.status(500).json({message:e.message||'Assistant failed.'});}});
app.get('/api/scans',authRequired,(req,res)=>res.json({scans:db.prepare('SELECT id,crop,label,confidence,severity,description,created_at FROM scans WHERE user_id=? ORDER BY id DESC LIMIT 50').all(req.userId)}));
app.get('/api/subsidies',authRequired,(req,res)=>{const q=String(req.query.q||'').toLowerCase(),state=String(req.query.state||'').toLowerCase(),crop=String(req.query.crop||'').toLowerCase();let rows=db.prepare('SELECT * FROM subsidies ORDER BY name').all();rows=rows.filter(x=>(!q||[x.name,x.category,x.eligibility,x.benefit].join(' ').toLowerCase().includes(q))&&(!state||!x.state||x.state.toLowerCase()===state)&&(!crop||!x.crop||x.crop.toLowerCase().includes(crop)));res.json({subsidies:rows});});
const frontendDir=path.resolve(ROOT,'../frontend');
app.use(express.static(frontendDir));
app.get('/',(req,res)=>res.sendFile(path.join(frontendDir,'index.html')));
app.use((err,req,res,next)=>{res.status(500).json({message:err.message||'Server error'});});
app.listen(PORT,()=>console.log(`AgriVision backend running on http://localhost:${PORT}`));
